### PR TITLE
Fix compatibility with mongoid 2.1.x 

### PR DESCRIPTION
**Pull request by y8**
This pull request fixes incompatibility with actual Mongoid and introduces completely refactored I18n module (again ;).

### CODE REVIEW

**Comment by y8** [comment]
This is more elegant variant. We push all localization logic to LocalizedFields class, so main module will be clean and simple.

**Comment by y8** [comment]
It passes all test, and I added one new example to be sure that i18n not touches other fields.

**Comment by krainboltgreene** [comment]
I'm liking this change. Using it on a pet project and it works well.

**Comment by Papipo** [comment]
Merged, sorry for being so slow.

**Comment by krainboltgreene** [comment]
Hey, no problem man, it's open source! Thanks for the hard work, it really helps out those of us looking for a good solution. Seriously.

**Pull request merged**
